// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/accrual/main.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	diploma "github.com/gam6itko/go-musthave-diploma/internal/diploma"
	gomock "github.com/golang/mock/gomock"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIClient) Get(orderID uint64) (*diploma.Accrual, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", orderID)
	ret0, _ := ret[0].(*diploma.Accrual)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIClientMockRecorder) Get(orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIClient)(nil).Get), orderID)
}
