POST localhost:8080/api/user/register
Content-Type: application/json


{
  "login": "{{$random.email}}",
  "password": "password"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response has Authorization header", function() {
        client.assert(response.headers.valueOf('Authorization') !== '', "No Authorization header");
    });
%}